version: '3.8'

services:
  # Development überrides
  chatilo-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - ./server:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

  chatilo-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      REACT_APP_API_URL: http://localhost:1113
      REACT_APP_SOCKET_URL: http://localhost:1113
    volumes:
      - ./client:/app
      - /app/node_modules
    command: ["npm", "start"]
    ports:
      - "1234:3000"
